mode:
  nni: false

data:
  path: ./data
  dataset: muv
  num_bond_features: 2
  num_atom_features: 2
  num_workers: 2

model:
  backbone: gnn # seq, gnn


device:
  cuda : 0

meta:
  num_atoms: 119
  selfsupervised_weight: 0
  contrastive_weight: 0.1
  alpha_s: 1
  alpha_e: 0.2
  beta: 0.1

train:
  random_seed: 7
  epochs: 2000
  batch_size: 64
  meta_lr: 0.001
  update_lr: 0.01
  decay: 0
  update_step: 1
  update_step_test: 1
  eval_epoch: 20

tasks:
  name: muv
  tox21:
    num_tasks: 12
    train_tasks: [0,1,2,3,4,5,6,7,8]
    
    test_tasks: [9,10,11]
    n_way: 2
    m_support: 20
    k_query: 32

  sider:
    num_tasks: 27
    train_tasks:
      [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20
        
      ]


    test_tasks: [21,22,23,24,25,26]
    # 23 24 26
    n_way: 2
    m_support: 10
    k_query: 32
  
  muv:
    num_tasks: 17
    train_tasks:
      [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11   
      ]

      # 77: 21 22 23 24 25 26
      # 81.5 19 20 21 24 25 26
      #
    test_tasks: [12,13, 14, 15, 16]
    # 23 24 26
    n_way: 2
    m_support: 10
    k_query: 32

logger:
  log: false
  log_dir: outputs
  mlflow:
    MLFLOW_TRACKING_URI: http://127.0.0.1:8889
    MLFLOW_EXPERIMENT_NAME: "FSADMET"
    REGISTERED_MODEL_NAME: "fsadmet"
